<?php
/**
 * _voice-reader.php — the "Pakinggan" player, shared by the three detail pages.
 *
 * Set before requiring:
 *   $__vrType (string)  'announcement' | 'event' | 'ordinance'
 *   $__vrRow  (array)   the content row, as the detail query returns it
 *   $__vrBodySelector (string|null)  element whose sentences get highlighted;
 *                                    defaults to [data-voice-body]
 *
 * ── What this is ──────────────────────────────────────────────────────────
 * One player, three languages, and a real narrator voice.
 *
 * The audio a resident hears is an MP3 generated by a proper text-to-speech
 * provider when staff published the post, cached per post per language. The
 * device's own speech engine is the fallback for a language whose MP3 does not
 * exist yet or has gone stale — it used to be the only source, and it is the
 * reason this feature still works with no provider key configured at all.
 *
 * ── Language ─────────────────────────────────────────────────────────────
 * The picker starts on whatever the header's FIL / EN / MN switch has chosen,
 * so the two never contradict each other on arrival. After that they are
 * independent on purpose: a resident reading in Filipino may well want to play
 * the Manobo track for an elder sitting beside them.
 *
 * A language with no translation is shown greyed out, not quietly filled in
 * with another language's text. An "English" button that speaks Filipino is a
 * bug, not a fallback.
 *
 * ── Manobo ───────────────────────────────────────────────────────────────
 * No provider on earth has an Agusan Manobo voice. Precedence is therefore:
 * a recording by a community member first, always; then a generated Filipino
 * voice reading the Manobo text, labelled next to the play button as an
 * approximation in all three languages; and the labelling is not negotiable.
 */

use App\Services\PostAudioService;

$__vrType = (string) ($__vrType ?? '');
$__vrRow  = (array)  ($__vrRow  ?? []);
$__vrBodySelector = $__vrBodySelector ?? '[data-voice-body]';

$__vrTracks = (new PostAudioService())->tracks($__vrType, $__vrRow);

// Nothing written in any language, and nothing recorded: render no player at
// all rather than a button that does nothing when pressed.
$__vrAnyTrack = false;
foreach ($__vrTracks as $__vrT) {
    if ($__vrT['available']) {
        $__vrAnyTrack = true;
        break;
    }
}
if (!$__vrAnyTrack) {
    return;
}

// Start on the language the page is already in, when there is anything to play
// in it; otherwise the first language that does have something.
$__vrDefault = current_locale();
if (!($__vrTracks[$__vrDefault]['available'] ?? false)) {
    foreach ($__vrTracks as $__vrCode => $__vrT) {
        if ($__vrT['available']) {
            $__vrDefault = $__vrCode;
            break;
        }
    }
}

$__vrHeading = match ($__vrType) {
    'event'     => t('voice_reader.title_event'),
    'ordinance' => t('voice_reader.title_ordinance'),
    default     => t('voice_reader.title_announcement'),
};

/*
 * Language labels are shown in the reader's own language, not in each
 * language's own name: someone who has the page in Filipino is looking for
 * "Ingles", not "English". The short code beside it is what makes the row
 * scannable at arm's length.
 */
$__vrLangNames = [
    'en'  => t('voice_reader.lang_en'),
    'fil' => t('voice_reader.lang_fil'),
    'msm' => t('voice_reader.lang_mn'),
];

// One URL per language, built server-side with route()/CSRF-free GET —
// exactly what the header switch already links to — so switching the page
// language from inside the player uses the one true mechanism the rest of
// the site uses, rather than a second, JS-only copy of set_locale().
$__vrLocaleUrls = [];
foreach (array_keys($__vrLangNames) as $__vrLc) {
    $__vrLocaleUrls[$__vrLc] = route('set-locale/' . $__vrLc);
}

$__vrConfig = [
    'type'          => $__vrType,
    'id'            => (int) ($__vrRow['id'] ?? 0),
    'defaultLocale' => $__vrDefault,
    'bodySelector'  => $__vrBodySelector,
    'rate'          => 1,
    'tracks'        => $__vrTracks,
    'localeUrls'    => $__vrLocaleUrls,
    'csrfToken'     => csrf_token(),
    'strings'       => [
        'no_voice'       => t('voice_reader.no_voice'),
        'speech_failed'  => t('voice_reader.speech_failed'),
        'audio_failed'   => t('voice_reader.audio_failed'),
        'status_playing' => t('voice_reader.status_playing'),
        'status_paused'  => t('voice_reader.status_paused'),
        'status_idle'    => t('voice_reader.status_idle'),
        'unavailable_in' => t('voice_reader.unavailable_in'),
        'source_human'   => t('voice_reader.source_human'),
        'source_ai'      => t('voice_reader.source_ai'),
        'source_approx'  => t('voice_reader.source_approx'),
        'source_device'  => t('voice_reader.source_device'),
        'source_dataset_mix' => t('voice_reader.source_dataset_mix'),
        'stale_recording'=> t('voice_reader.stale_recording'),
        'languages'      => $__vrLangNames,
        'translating'    => t('voice_reader.translating'),
        'translate_now'  => t('voice_reader.translate_now'),
        'translate_failed' => t('voice_reader.translate_failed'),
    ],
];

// One engine file per request, however many players a page ever carries.
$__vrEmitJs = !defined('BG_VOICE_JS_EMITTED');
if ($__vrEmitJs) {
    define('BG_VOICE_JS_EMITTED', true);
}
?>

<?php if ($__vrEmitJs): ?>
<?php /* Not deferred: Alpine is, and this must define voiceReader() first. */ ?>
<script src="<?= e(asset_v('assets/js/voice-reader.js')) ?>"></script>
<?php endif; ?>

<div class="voice-reader"
     x-data="voiceReader()"
     x-show="available"
     style="display:none;"
     x-cloak>

    <script type="application/json" data-voice-config><?= json_encode(
        $__vrConfig,
        JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE
    ) ?></script>

    <?php /* The only audio element on the page. No controls attribute: the
             card's own buttons drive it, so there is never a second play
             button and a second timeline disagreeing with the first. */ ?>
    <audio data-voice-audio
           preload="none"
           style="display:none;"
           @timeupdate="onAudioProgress($event)"
           @loadedmetadata="onAudioReady($event)"
           @play="onAudioPlay()"
           @pause="onAudioPause()"
           @ended="onAudioEnded()"
           @error="onAudioError()"></audio>

    <div class="voice-card">

        <!-- ── The one control that matters ────────────────────────────────
             Big, first, and directly under the headline. An elderly resident
             should not have to scroll past share buttons to find it. -->
        <div class="voice-row">
            <button type="button"
                    class="voice-play"
                    @click="toggle()"
                    :disabled="!canPlay"
                    :aria-pressed="status === 'playing' ? 'true' : 'false'">
                <i class="bi" :class="status === 'playing' ? 'bi-pause-fill' : 'bi-play-fill'" aria-hidden="true"></i>
                <span x-show="status !== 'playing'"><?= e(t('voice_reader.listen')) ?></span>
                <span x-show="status === 'playing'" x-cloak><?= e(t('voice_reader.pause')) ?></span>
            </button>

            <div class="voice-meta">
                <p class="voice-heading"><?= e($__vrHeading) ?></p>
                <p class="voice-sub" x-text="sourceLabel"></p>
            </div>

            <button type="button"
                    class="voice-stop"
                    x-show="status !== 'idle'"
                    x-cloak
                    @click="stop()"
                    :aria-label="<?= e(json_encode(t('voice_reader.stop'))) ?>">
                <i class="bi bi-stop-fill" aria-hidden="true"></i>
                <span><?= e(t('voice_reader.stop')) ?></span>
            </button>
        </div>

        <!-- ── Language ────────────────────────────────────────────────────
             Picking a language here also switches the whole page to it (the
             same set_locale() the header switch uses), so the two can never
             disagree about what is on screen versus what is being read.

             A language with no translation yet is never a dead end: it stays
             pressable, and pressing it asks for that one translation on the
             spot (text only — see VoiceController::translateNow()) instead of
             greying out with nothing the resident can do about it. -->
        <div class="voice-langs" role="group" aria-label="<?= e(t('voice_reader.lang_label')) ?>">
            <span class="voice-speed-label"><?= e(t('voice_reader.lang_label')) ?></span>
            <?php foreach (['fil', 'en', 'msm'] as $__vrCode):
                $__vrT = $__vrTracks[$__vrCode] ?? ['available' => false]; ?>
            <button type="button"
                    class="voice-lang-btn"
                    :class="{
                        'is-active': locale === '<?= $__vrCode ?>',
                        'is-translating': translating === '<?= $__vrCode ?>',
                    }"
                    :aria-pressed="locale === '<?= $__vrCode ?>' ? 'true' : 'false'"
                    :disabled="translating === '<?= $__vrCode ?>'"
                    <?php if (!$__vrT['available']): ?>
                    :title="translating === '<?= $__vrCode ?>' ? <?= e(json_encode(t('voice_reader.translating'))) ?> : <?= e(json_encode(t('voice_reader.translate_now'))) ?>"
                    <?php else: ?>
                    title="<?= e($__vrLangNames[$__vrCode]) ?>"
                    <?php endif; ?>
                    @click="chooseLanguage('<?= $__vrCode ?>')">
                <span class="voice-lang-code"><?= e(locale_short_code($__vrCode)) ?></span>
                <span class="voice-lang-name">
                    <template x-if="translating !== '<?= $__vrCode ?>'"><span><?= e($__vrLangNames[$__vrCode]) ?></span></template>
                    <template x-if="translating === '<?= $__vrCode ?>'"><span><?= e(t('voice_reader.translating')) ?></span></template>
                </span>
                <?php if (!$__vrT['available']): ?>
                <i class="bi bi-magic voice-lang-hint" aria-hidden="true"></i>
                <?php endif; ?>
            </button>
            <?php endforeach; ?>
        </div>

        <?php
        /*
         * Manobo missing, said specifically.
         *
         * A greyed-out button with a tooltip is not enough here: Manobo is the
         * language most likely to be absent, and "unavailable" reads as "this
         * is broken" when the real answer is "nobody has written it yet" —
         * which is actionable, and which the barangay can fix by typing it.
         * The Filipino reading is offered in the same breath rather than
         * leaving the resident with nothing.
         */
        $__vrMnMissing = !($__vrTracks['msm']['available'] ?? false);
        $__vrFilOffer  = (bool) ($__vrTracks['fil']['available'] ?? false);
        ?>
        <?php if ($__vrMnMissing): ?>
        <p class="voice-notice voice-notice-approx">
            <i class="bi bi-translate" aria-hidden="true"></i>
            <span>
                <?= e(t('voice_reader.mn_missing')) ?>
                <?php if ($__vrFilOffer): ?>
                <button type="button" class="voice-inline-link" @click="setLocale('fil')">
                    <?= e(t('voice_reader.listen_in_filipino')) ?>
                </button>
                <?php endif; ?>
            </span>
        </p>
        <?php endif; ?>

        <!-- Progress -->
        <div class="voice-track"
             role="progressbar"
             aria-valuemin="0"
             aria-valuemax="100"
             :aria-valuenow="Math.round(progress)"
             :aria-label="<?= e(json_encode(t('voice_reader.progress_label'))) ?>">
            <div class="voice-fill" :style="'width:' + progress + '%'"></div>
        </div>

        <!-- Speed. Older listeners very often want it slower, so it is a
             visible control rather than something in a settings menu. -->
        <div class="voice-speed" role="group" aria-label="<?= e(t('voice_reader.speed')) ?>">
            <span class="voice-speed-label"><?= e(t('voice_reader.speed')) ?></span>
            <?php foreach ([
                ['0.75', t('voice_reader.speed_slow')],
                ['1',    t('voice_reader.speed_normal')],
                ['1.25', t('voice_reader.speed_fast')],
            ] as [$__vrRate, $__vrRateLabel]): ?>
            <button type="button"
                    class="voice-speed-btn"
                    :class="rate === <?= $__vrRate ?> ? 'is-active' : ''"
                    :aria-pressed="rate === <?= $__vrRate ?> ? 'true' : 'false'"
                    @click="setRate(<?= $__vrRate ?>)">
                <?= e($__vrRateLabel) ?>
            </button>
            <?php endforeach; ?>
        </div>

        <!-- ── Manobo source switch ────────────────────────────────────────
             Shown only when a post has both. The community recording stays
             the default; this exists so hearing the generated voice never
             requires deleting someone's recording to get at it. -->
        <div class="voice-speed" x-show="hasAlternateSource" x-cloak
             role="group" aria-label="<?= e(t('voice_reader.source_label')) ?>">
            <span class="voice-speed-label"><?= e(t('voice_reader.source_label')) ?></span>
            <button type="button"
                    class="voice-speed-btn"
                    :class="preferHuman ? 'is-active' : ''"
                    :aria-pressed="preferHuman ? 'true' : 'false'"
                    @click="useSource(true)">
                <i class="bi bi-mic-fill" aria-hidden="true"></i> <?= e(t('voice_reader.source_switch_human')) ?>
            </button>
            <button type="button"
                    class="voice-speed-btn"
                    :class="!preferHuman ? 'is-active' : ''"
                    :aria-pressed="!preferHuman ? 'true' : 'false'"
                    @click="useSource(false)">
                <i class="bi bi-robot" aria-hidden="true"></i> <?= e(t('voice_reader.source_switch_ai')) ?>
            </button>
        </div>

        <!-- ── The approximation label ─────────────────────────────────────
             Beside the play button, not in a footnote. A Manobo speaker has a
             right to know before they press play that what they are about to
             hear is a Filipino voice doing its best with their language. -->
        <p class="voice-notice voice-notice-approx" x-show="showApproxLabel" x-cloak>
            <i class="bi bi-robot" aria-hidden="true"></i>
            <span><?= e(t('voice_reader.approx_explain')) ?></span>
        </p>

        <p class="voice-notice" x-show="notice" x-cloak>
            <i class="bi bi-info-circle" aria-hidden="true"></i>
            <span x-text="notice"></span>
        </p>
    </div>

    <!-- ── Sticky mini player ──────────────────────────────────────────────
         Playback controls have to stay reachable while the resident scrolls
         through the post; hunting back up the page for the pause button is
         exactly the problem this feature exists to remove. -->
    <div class="voice-mini" x-show="status !== 'idle'" x-cloak>
        <button type="button"
                class="voice-mini-btn"
                @click="toggle()"
                :aria-label="status === 'playing' ? <?= e(json_encode(t('voice_reader.pause'))) ?> : <?= e(json_encode(t('voice_reader.listen'))) ?>">
            <i class="bi" :class="status === 'playing' ? 'bi-pause-fill' : 'bi-play-fill'" aria-hidden="true"></i>
        </button>

        <div class="voice-mini-body">
            <p class="voice-mini-title">
                <?= e($__vrHeading) ?>
                <span class="voice-mini-lang" x-text="localeCode"></span>
            </p>
            <div class="voice-track voice-track-mini">
                <div class="voice-fill" :style="'width:' + progress + '%'"></div>
            </div>
        </div>

        <button type="button"
                class="voice-mini-btn voice-mini-stop"
                @click="stop()"
                :aria-label="<?= e(json_encode(t('voice_reader.stop'))) ?>">
            <i class="bi bi-x-lg" aria-hidden="true"></i>
        </button>
    </div>

    <!-- Status for screen readers; the visual equivalent is the button icon. -->
    <p class="voice-sr-only" aria-live="polite" x-text="statusText"></p>
</div>
