<?php
declare(strict_types=1);

/**
 * Seed 5 announcements, 5 events and 5 ordinances designed as a test matrix.
 *
 *   php tools/seed-sample-content.php                    # seed (or update)
 *   php tools/seed-sample-content.php --with-notifications
 *   php tools/seed-sample-content.php --no-translate     # skip the one API call
 *   php tools/seed-sample-content.php --purge            # remove everything
 *   php tools/seed-sample-content.php --list             # what is seeded now
 *
 * Not a migration, deliberately. Demo content must never ride along into a
 * real deployment, and runPendingMigrations() replays every migration file on
 * every database connection — a seeder in there would re-create fifteen fake
 * barangay notices on every page load.
 *
 * ── The three safety rules this script is built around ──────────────────
 *
 * 1. Everything it writes is flagged is_sample = 1 (migration 025) and every
 *    generated image says SAMPLE across it. --purge then removes exactly
 *    these rows and their files, matched on the flag rather than guessed from
 *    titles. This is a live government notice board; a seeded storm-surge
 *    advisory that cannot be told apart from a real one is a safety problem,
 *    not a tidiness problem.
 *
 * 2. Nothing goes out. The admin save path broadcasts notifications and can
 *    fire SMS through SemaphoreSmsService — fifteen posts would mean fifteen
 *    SMS broadcasts to every registered resident. This script writes through
 *    the models directly, never the controllers, and additionally clears the
 *    Semaphore credentials from the environment for the duration of the run
 *    so that nothing reached indirectly can send either. Notifications are
 *    opt-in via --with-notifications, so that path can be tested on purpose
 *    rather than by accident.
 *
 * 3. Ordinances are legal instruments. Every sample one is prefixed [SAMPLE]
 *    in both its title and its number, its body says plainly that it is
 *    illustrative, and its PDF carries a red SAMPLE banner on page one.
 *
 * ── What it still shares with the real save path ────────────────────────
 *
 * Slugs come from generate_slug() + Model::uniqueSlug(). Bodies go through
 * PostHtml::purify() — the same configuration the admin form uses, which is
 * the point: sample #4 is deliberately full of pasted inline colours and they
 * have to be gone by the time they reach the database. Images and PDFs are
 * written through FileService::storeFetched(), so MIME sniffing, the
 * randomised filename and the delete path all get exercised too.
 */

$root = \dirname(__DIR__);
require $root . '/vendor/autoload.php';
if (class_exists(\Dotenv\Dotenv::class) && is_file($root . '/.env')) {
    \Dotenv\Dotenv::createImmutable($root)->safeLoad();
}
require $root . '/app/helpers.php';
require $root . '/config/database.php';
require __DIR__ . '/sample-content/media.php';
require __DIR__ . '/sample-content/content.php';

use App\Models\Announcement;
use App\Models\Event;
use App\Models\Ordinance;
use App\Services\FileService;
use App\Services\NotificationService;
use App\Services\PostHtml;

/*
 * Safety rule 2, enforced before anything else runs.
 *
 * Belt and braces: this script does not call the controllers, so it does not
 * reach the SMS path at all. But "does not currently reach it" is a property
 * of today's code, and a seeder is exactly the kind of script someone later
 * points at a controller. Without a key, SemaphoreSmsService::isConfigured()
 * is false and send()/sendBulk() refuse before any request is built.
 */
foreach (['SEMAPHORE_API_KEY', 'SEMAPHORE_SENDER_NAME', 'SEMAPHORE_API_URL'] as $key) {
    unset($_ENV[$key], $_SERVER[$key]);
    putenv($key);
}
$_ENV['SEMAPHORE_TEST_MODE'] = 'true';

$args             = array_slice($argv, 1);
$purge            = in_array('--purge', $args, true);
$list             = in_array('--list', $args, true);
$withNotification = in_array('--with-notifications', $args, true);
$GLOBALS['skipTranslate'] = in_array('--no-translate', $args, true);

const SAMPLE_IMAGE_DIR = 'announcements';   // FileService subdirectory
const SAMPLE_PDF_DIR   = 'ordinances';

// ── Helpers ─────────────────────────────────────────────────────────────

function say(string $line = ''): void
{
    echo $line . "\n";
}

function heading(string $text): void
{
    say();
    say('── ' . $text . ' ' . str_repeat('─', max(0, 68 - mb_strlen($text))));
}

/** Delete a stored upload, ignoring one that is already gone. */
function drop_upload(?string $url): bool
{
    if ($url === null || trim($url) === '') {
        return false;
    }
    try {
        (new FileService())->delete($url);
        return true;
    } catch (\Throwable $e) {
        say('    could not remove ' . $url . ': ' . $e->getMessage());
        return false;
    }
}

/**
 * Store generated bytes through the ordinary upload path.
 *
 * storeFetched() sniffs the real MIME type from the content with finfo, so a
 * generated PNG or PDF is validated exactly as a staff member's upload is.
 */
function store_bytes(string $bytes, string $dir, string $mime): ?string
{
    try {
        return (new FileService())->storeFetched($bytes, $dir, [$mime], 8 * 1024 * 1024);
    } catch (\Throwable $e) {
        say('    upload failed: ' . $e->getMessage());
        return null;
    }
}

// ── Author ──────────────────────────────────────────────────────────────

/**
 * Attribute the samples to a real staff account.
 *
 * Never invents one. A seeder that quietly creates a user on a government
 * system is creating a login nobody knows about, and the author name shows on
 * every post — a fabricated "Juan Dela Cruz" would look like a real employee.
 */
function sample_author(): ?array
{
    $stmt = db()->query(
        "SELECT id, full_name, role FROM users
          WHERE role IN ('staff','admin','superadmin') AND status = 'verified'
          ORDER BY CASE role WHEN 'staff' THEN 1 WHEN 'admin' THEN 2 WHEN 'superadmin' THEN 3 ELSE 4 END, id
          LIMIT 1"
    );

    return $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
}

// ── Purge ───────────────────────────────────────────────────────────────

function purge(): void
{
    heading('Removing sample content');

    $tables = [
        'announcements' => ['cover_image_url'],
        'events'        => ['cover_image_url'],
        'ordinances'    => ['file_url'],
    ];

    $rows = 0;
    $files = 0;

    foreach ($tables as $table => $fileColumns) {
        try {
            $sample = db()->query("SELECT * FROM {$table} WHERE is_sample = 1")->fetchAll(PDO::FETCH_ASSOC);
        } catch (\Throwable $e) {
            say("  {$table}: skipped ({$e->getMessage()})");
            continue;
        }

        foreach ($sample as $row) {
            foreach ($fileColumns as $column) {
                if (drop_upload($row[$column] ?? null)) {
                    $files++;
                }
            }
            // Generated Manobo/te audio, if the voice reader ever cached any
            // for these rows, is cleaned up by its own service.
            if (class_exists(\App\Services\PostAudioService::class)) {
                $type = ['announcements' => 'announcement', 'events' => 'event', 'ordinances' => 'ordinance'][$table];
                try {
                    \App\Services\PostAudioService::purgeFor($type, (int) $row['id']);
                } catch (\Throwable $e) {
                    // Non-fatal: a missing cache is the normal case.
                }
            }
        }

        // Notifications pointing at rows that are about to vanish would leave
        // residents with bell entries that 404 when tapped.
        $ids = array_column($sample, 'id');
        if ($ids !== []) {
            $type = ['announcements' => 'announcement', 'events' => 'event', 'ordinances' => 'ordinance'][$table];
            $in   = implode(',', array_fill(0, count($ids), '?'));
            try {
                db()->prepare("DELETE FROM notifications WHERE related_type = ? AND related_id IN ({$in})")
                    ->execute(array_merge([$type], $ids));
            } catch (\Throwable $e) {
                say('  notification cleanup: ' . $e->getMessage());
            }
        }

        $deleted = db()->exec("DELETE FROM {$table} WHERE is_sample = 1");
        $rows   += (int) $deleted;
        say(sprintf('  %-14s %d row(s) removed', $table, (int) $deleted));
    }

    say();
    say("Removed {$rows} row(s) and {$files} generated file(s).");

    // Prove it, rather than asserting it.
    $left = 0;
    foreach (array_keys($tables) as $table) {
        try {
            $left += (int) db()->query("SELECT COUNT(*) FROM {$table} WHERE is_sample = 1")->fetchColumn();
        } catch (\Throwable $e) {
            // column gone == nothing to count
        }
    }
    say($left === 0 ? 'Verified: no sample rows remain.' : "*** {$left} sample row(s) STILL PRESENT ***");
}

// ── List ────────────────────────────────────────────────────────────────

function listSamples(): void
{
    heading('Sample content currently in the database');

    // Ordinances are addressed by id, not by slug — they have no slug column.
    foreach (['announcements' => 'slug', 'events' => 'slug', 'ordinances' => 'ordinance_no'] as $table => $ref) {
        try {
            $rows = db()->query("SELECT id, title, {$ref} AS ref FROM {$table} WHERE is_sample = 1 ORDER BY id")
                        ->fetchAll(PDO::FETCH_ASSOC);
        } catch (\Throwable $e) {
            say("  {$table}: " . $e->getMessage());
            continue;
        }

        say(sprintf('  %s (%d)', $table, count($rows)));
        foreach ($rows as $row) {
            printf("    #%-4d %s\n", $row['id'], mb_substr((string) $row['title'], 0, 66));
        }
    }
}

// ── Seed ────────────────────────────────────────────────────────────────

/**
 * Find an existing sample row by the stable key stored in its slug, so a
 * second run updates instead of duplicating.
 */
function find_sample(string $table, string $slugOrNumber, string $column = 'slug'): ?array
{
    $stmt = db()->prepare("SELECT * FROM {$table} WHERE {$column} = ? AND is_sample = 1 LIMIT 1");
    $stmt->execute([$slugOrNumber]);

    return $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
}

function seedAnnouncements(array $author, bool $notify): array
{
    heading('Announcements');
    $made = [];

    foreach (sample_announcements() as $spec) {
        $slug = generate_slug($spec['title']);
        $slug = Announcement::uniqueSlug($slug);

        $existing = find_sample('announcements', $slug);
        // A title change would move the slug, so also look by the stable key.
        if (!$existing) {
            $stmt = db()->prepare("SELECT * FROM announcements WHERE is_sample = 1 AND slug LIKE ? LIMIT 1");
            $stmt->execute([generate_slug($spec['title']) . '%']);
            $existing = $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
        }

        // The purifier runs on the way in, exactly as it does on the admin
        // form. Sample #4 arrives full of pasted inline colours on purpose.
        $rawLength  = strlen($spec['body']);
        $body       = PostHtml::purify($spec['body']);
        $strippedPx = $rawLength - strlen($body);

        $publishedAt = date('Y-m-d H:i:s', strtotime("-{$spec['days_ago']} days +" . random_int(8, 16) . ' hours'));

        // The cover is settled before the write, because Announcement::update()
        // sets cover_image_url from what it is given — omitting it on a re-run
        // would blank the cover rather than leave it alone. Rows whose whole
        // purpose is to have no cover keep null.
        $cover = $existing['cover_image_url'] ?? null;
        if ($spec['palette'] !== null && ($cover === null || $cover === '')) {
            $cover = store_bytes(
                sample_cover_png($spec['title'], $spec['palette'], $spec['kicker']),
                SAMPLE_IMAGE_DIR,
                'image/png'
            );
        }

        if ($existing) {
            $id = (int) $existing['id'];
            Announcement::update($id, [
                'title'           => $spec['title'],
                'body'            => $body,
                'category'        => $spec['category'],
                'urgency'         => $spec['urgency'],
                'status'          => 'published',
                'published_at'    => $publishedAt,
                'cover_image_url' => $cover,
            ]);
            $verb = 'updated';
        } else {
            $id = Announcement::create([
                'title'           => $spec['title'],
                'slug'            => $slug,
                'body'            => $body,
                'category'        => $spec['category'],
                'urgency'         => $spec['urgency'],
                'author_id'       => (int) $author['id'],
                'status'          => 'published',
                'published_at'    => $publishedAt,
                'cover_image_url' => $cover,
            ]);
            $verb = 'created';
        }

        db()->prepare('UPDATE announcements SET is_sample = 1 WHERE id = ?')->execute([$id]);

        // Source language. 'auto' on the medical mission row so the detector
        // has to read the English text and file it correctly — that is the
        // case this row exists to prove.
        $lang = $spec['source_lang'] === 'auto'
            ? \App\Services\TranslationService::resolveSourceLang(null, $spec['title'], $body)
            : $spec['source_lang'];
        Announcement::setSourceLang($id, $lang);

        if (!empty($spec['manobo'])) {
            Announcement::updateManobo($id, $spec['manobo']['title'], $spec['manobo']['body']);
            \App\Services\TranslationService::flagAuto('announcement', $id, 'manobo_is_auto', false);
        }

        /*
         * Machine translation, per the matrix rather than for everything.
         *
         * Only the row whose stated purpose is "proves English -> Filipino
         * auto-translation works" is translated on a default run. Translating
         * all five would spend the free service's daily per-IP allowance on
         * content nobody is reading, and would destroy the rows that exist
         * precisely to show what a missing translation looks like.
         *
         * --no-translate skips even that, for a fast offline seed.
         */
        $translated = null;
        if (!$GLOBALS['skipTranslate'] && (!empty($spec['auto_other']) || !empty($spec['auto_manobo']))) {
            $auto = \App\Services\TranslationService::autoTranslateFrom(
                'announcement',
                $id,
                $spec['title'],
                $body,
                $lang,
                !empty($spec['auto_other']),
                !empty($spec['auto_manobo'])
            );
            $other      = $lang === 'fil' ? 'EN' : 'FIL';
            $translated = sprintf('%s %s, MN %s',
                $other, $auto['other'] ? 'ok' : 'failed',
                $auto['manobo'] ? 'ok' : 'failed');
        }

        $made[] = [
            'id'     => $id,
            'slug'   => $existing['slug'] ?? $slug,
            'title'  => $spec['title'],
            'covers' => $spec['covers'],
            'verb'   => $verb,
            'lang'   => $lang,
            'note'   => $strippedPx > 0 ? "purifier removed {$strippedPx} bytes of inline styling" : null,
        ];

        printf("  %-8s #%-4d %s\n", $verb, $id, mb_substr($spec['title'], 0, 58));
        printf("           source_lang=%s%s%s\n",
            $lang,
            $strippedPx > 0 ? "  (stripped {$strippedPx} bytes of pasted styling)" : '',
            $translated !== null ? "  translated: {$translated}" : '');

        if ($notify && $verb === 'created') {
            $n = (new NotificationService())->broadcast(
                'announcement',
                '[SAMPLE] ' . $spec['title'],
                'Sample content for testing.',
                $id,
                'announcement'
            );
            printf("           %d notification(s) created\n", $n);
        }
    }

    return $made;
}

function seedEvents(array $author, bool $notify): array
{
    heading('Events');
    $made = [];

    foreach (sample_events() as $spec) {
        $slug     = Announcement::uniqueSlug(generate_slug($spec['title']));
        $existing = find_sample('events', $slug);
        if (!$existing) {
            $stmt = db()->prepare("SELECT * FROM events WHERE is_sample = 1 AND slug LIKE ? LIMIT 1");
            $stmt->execute([generate_slug($spec['title']) . '%']);
            $existing = $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
        }

        $description = PostHtml::purify($spec['description']);

        // Dates are offsets from now, so the status and the date always agree
        // however long after seeding the site is opened. "Ongoing" starts a
        // couple of hours ago so it is genuinely in progress right now.
        $startsAt = $spec['status'] === 'ongoing'
            ? date('Y-m-d H:i:s', strtotime('-2 hours'))
            : date('Y-m-d H:i:s', strtotime(sprintf('%+d days', $spec['starts_in_days'])) );
        if ($spec['status'] !== 'ongoing') {
            $startsAt = date('Y-m-d 09:00:00', strtotime(sprintf('%+d days', $spec['starts_in_days'])));
        }
        $endsAt = date('Y-m-d H:i:s', strtotime($startsAt . ' +' . $spec['duration_hours'] . ' hours'));

        $fields = [
            'title'       => $spec['title'],
            'slug'        => $existing['slug'] ?? $slug,
            'description' => $description,
            'venue'       => $spec['venue'],
            'latitude'    => $spec['lat'],
            'longitude'   => $spec['lng'],
            'event_date'  => $startsAt,
            'end_date'    => $endsAt,
            'status'      => $spec['status'],
        ];

        if ($existing) {
            $id = (int) $existing['id'];
            Event::update($id, $fields);
            $verb = 'updated';
        } else {
            $id = Event::create($fields + ['created_by' => (int) $author['id']]);
            $verb = 'created';
        }

        db()->prepare('UPDATE events SET is_sample = 1 WHERE id = ?')->execute([$id]);
        Event::setSourceLang($id, 'fil');

        $row = Event::find($id);
        if ($spec['palette'] !== null && empty($row['cover_image_url'])) {
            $png = sample_cover_png($spec['title'], $spec['palette'], $spec['kicker']);
            $url = store_bytes($png, 'events', 'image/png');
            if ($url !== null) {
                Event::updateCover($id, $url);
            }
        }

        $made[] = [
            'id' => $id, 'slug' => $fields['slug'], 'title' => $spec['title'],
            'covers' => $spec['covers'], 'verb' => $verb,
        ];

        printf("  %-8s #%-4d %-52s [%s]\n", $verb, $id, mb_substr($spec['title'], 0, 52), $spec['status']);

        if ($notify && $verb === 'created') {
            $n = (new NotificationService())->broadcast(
                'event', '[SAMPLE] ' . $spec['title'], 'Sample content for testing.', $id, 'event'
            );
            printf("           %d notification(s) created\n", $n);
        }
    }

    return $made;
}

function seedOrdinances(array $author, bool $notify): array
{
    heading('Ordinances');
    $made = [];

    foreach (sample_ordinances() as $spec) {
        $existing = find_sample('ordinances', $spec['number'], 'ordinance_no');

        $enactedYears = $spec['enacted_years_ago'] ?? 0;
        $enacted = date('Y-m-d', strtotime("-{$spec['days_ago']} days -{$enactedYears} years"));

        $fields = [
            'title'        => $spec['title'],
            'ordinance_no' => $spec['number'],
            'description'  => $spec['description'],
            'category'     => $spec['category'],
            'enacted_date' => $enacted,
            'status'       => $spec['status'],
        ];

        // The PDF is settled before the write, for the same reason the
        // announcement cover is: Ordinance::updateRecord() sets file_url from
        // what it is handed, so omitting it on a re-run blanks the column and
        // orphans the file on disk — where --purge can no longer find it.
        $pdfUrl = $existing['file_url'] ?? null;
        if ($pdfUrl === null || trim($pdfUrl) === '') {
            $pdfUrl = store_bytes(
                sample_pdf($spec['title'], sample_pdf_lines($spec)),
                SAMPLE_PDF_DIR,
                'application/pdf'
            );
            if ($pdfUrl === null) {
                say('    skipped: could not store the PDF');
                continue;
            }
        }
        $fields['file_url'] = $pdfUrl;

        if ($existing) {
            $id = (int) $existing['id'];
            Ordinance::updateRecord($id, $fields);
            $verb = 'updated';
        } else {
            $id = Ordinance::create($fields + ['uploaded_by' => (int) $author['id']]);
            $verb = 'created';
        }

        db()->prepare('UPDATE ordinances SET is_sample = 1 WHERE id = ?')->execute([$id]);
        Ordinance::setSourceLang($id, 'fil');

        // Only one row gets a cached summary; the rest exist to exercise the
        // "Summarize with AI" button, including how it behaves with no credits.
        if ($spec['summary'] !== null) {
            db()->prepare('UPDATE ordinances SET ai_summary = ?, ai_summary_at = NOW() WHERE id = ?')
                ->execute([$spec['summary'], $id]);
        }

        if (!empty($spec['manobo'])) {
            Ordinance::updateManobo($id, $spec['manobo']['title'], $spec['manobo']['desc']);
            \App\Services\TranslationService::flagAuto('ordinance', $id, 'manobo_is_auto', false);
        }

        // Backdate so date sorting and the archive view have real spread.
        db()->prepare('UPDATE ordinances SET created_at = ? WHERE id = ?')
            ->execute([date('Y-m-d H:i:s', strtotime("-{$spec['days_ago']} days")), $id]);

        $made[] = [
            'id' => $id, 'title' => $spec['title'], 'covers' => $spec['covers'], 'verb' => $verb,
        ];

        printf("  %-8s #%-4d %-50s [%s]\n", $verb, $id, mb_substr($spec['title'], 0, 50), $spec['status']);

        if ($notify && $verb === 'created') {
            $n = (new NotificationService())->broadcast(
                'ordinance', '[SAMPLE] ' . $spec['title'], 'Sample content for testing.', $id, 'ordinance'
            );
            printf("           %d notification(s) created\n", $n);
        }
    }

    return $made;
}

/** @return list<string> Body lines for a sample ordinance PDF. */
function sample_pdf_lines(array $spec): array
{
    return [
        '',
        'This document was generated automatically for testing the BarangGabay',
        'system. It is NOT a real barangay ordinance and has no legal effect.',
        '',
        'Reference: ' . $spec['number'],
        'Category:  ' . $spec['category'],
        'Status:    ' . strtoupper($spec['status']),
        '',
        'Summary of the illustrative content:',
        '',
        ...sample_wrap(strip_tags($spec['description']), 78),
        '',
        'Barangay Bayogo, Madrid, Surigao del Sur',
        '',
        'Remove this document and its database row with:',
        '    php tools/seed-sample-content.php --purge',
    ];
}

// ── Main ────────────────────────────────────────────────────────────────

$pdo = db();   // also applies migration 025

if ($list) {
    listSamples();
    exit(0);
}

if ($purge) {
    purge();
    exit(0);
}

$author = sample_author();
if ($author === null) {
    say('No verified staff, admin or superadmin account exists to attribute these posts to.');
    say('This script will not invent one — a user created quietly by a seeder is a login');
    say('nobody knows about, and the author name is shown on every post.');
    say('Create a staff account first, then run this again.');
    exit(1);
}

say('BarangGabay — sample content seeder');
say('Author:        ' . $author['full_name'] . ' (' . $author['role'] . ', id ' . $author['id'] . ')');
say('Notifications: ' . ($withNotification ? 'ON (--with-notifications)' : 'off — pass --with-notifications to test that path'));
say('SMS:           suppressed (Semaphore credentials cleared for this run)');
say('Translation:   ' . ($GLOBALS['skipTranslate']
    ? 'skipped (--no-translate)'
    : 'only the row that exists to prove it works; the rest stay untranslated on purpose'));

$announcements = seedAnnouncements($author, $withNotification);
$events        = seedEvents($author, $withNotification);
$ordinances    = seedOrdinances($author, $withNotification);

// ── Summary ─────────────────────────────────────────────────────────────

$base = rtrim((string) ($_ENV['APP_URL'] ?? 'http://localhost:8080/BarangGabay/public'), '/');

heading('What to click, and what each post is testing');

say();
say('ANNOUNCEMENTS');
foreach ($announcements as $i => $item) {
    say(sprintf("  %d. %s", $i + 1, mb_substr($item['title'], 0, 64)));
    say('     ' . $base . '/announcements/' . $item['slug']);
    say('     tests: ' . $item['covers']);
    if ($item['note']) {
        say('     note:  ' . $item['note']);
    }
}

say();
say('EVENTS');
foreach ($events as $i => $item) {
    say(sprintf("  %d. %s", $i + 1, mb_substr($item['title'], 0, 64)));
    say('     ' . $base . '/events/' . $item['slug']);
    say('     tests: ' . $item['covers']);
}

say();
say('ORDINANCES');
foreach ($ordinances as $i => $item) {
    say(sprintf("  %d. %s", $i + 1, mb_substr($item['title'], 0, 64)));
    say('     ' . $base . '/ordinances/' . $item['id']);
    say('     tests: ' . $item['covers']);
}

heading('Teardown');
say('  php tools/seed-sample-content.php --purge');
say('  Removes every is_sample row and the images and PDFs they reference.');
say();
